name: Deploy to server

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello World!"


  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 2 
        run: echo "Hello World Again!"