name: Playing with artifacts

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.myVariable}} "

    steps:
      - name: Creating file
        run: |
          echo "Testing file, hello" >> test.log

      - name: Loading file
        uses: actions/upload-artifact@v4
        with:
          name: test-file
          path: test.log


  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v4
        with:
          name: test-file

      - name: Cat file
        run: cat test.log