name: Strategy

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hola", "Codigo Facilito", "Bootcamp GitHub Actions"]

    steps:
      - name: Print message
        run: echo ${{ matrix.message }}